# Fix Next.js 16 - middleware to proxy + edge-safe auth

$ErrorActionPreference = "Stop"

if (-not (Test-Path "package.json")) {
    Write-Host "ERRO: corre dentro de xenco-surfshop" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Aplicando fix Next.js 16..." -ForegroundColor Cyan
Write-Host ""

# Apagar middleware.ts antigo (foi substituido por proxy.ts)
if (Test-Path "src/middleware.ts") {
    Remove-Item "src/middleware.ts" -Force
    Write-Host "  OK Apagado src/middleware.ts" -ForegroundColor Yellow
}

# src/auth.config.ts
$b64 = "aW1wb3J0IHR5cGUgeyBOZXh0QXV0aENvbmZpZyB9IGZyb20gIm5leHQtYXV0aCI7CmltcG9ydCBHb29nbGUgZnJvbSAibmV4dC1hdXRoL3Byb3ZpZGVycy9nb29nbGUiOwoKLyoqCiAqIENvbmZpZ3VyYcOnw6NvIGJhc2UgZG8gTmV4dEF1dGgg4oCUIEVkZ2Utc2FmZS4KICoKICogRXN0ZSBmaWNoZWlybyBOw4NPIGltcG9ydGEgTW9uZ29vc2UsIGJjcnlwdCwgb3UgcXVhbHF1ZXIKICogY29pc2EgcXVlIHVzZSBOb2RlLmpzIEFQSXMuIFBvZGUgc2VyIHVzYWRvIG5vIG1pZGRsZXdhcmUvcHJveHkKICogZSBlZGdlIHJ1bnRpbWUuCiAqCiAqIE8gcHJvdmlkZXIgQ3JlZGVudGlhbHMgKHF1ZSB1c2EgYmNyeXB0KSBlc3TDoSBlbSBhdXRoLnRzIGFwZW5hcy4KICovCmV4cG9ydCBkZWZhdWx0IHsKICBwYWdlczogewogICAgc2lnbkluOiAiL2xvZ2luIiwKICAgIGVycm9yOiAiL2xvZ2luIiwKICB9LAoKICBwcm92aWRlcnM6IFsKICAgIEdvb2dsZSh7CiAgICAgIGNsaWVudElkOiBwcm9jZXNzLmVudi5BVVRIX0dPT0dMRV9JRCwKICAgICAgY2xpZW50U2VjcmV0OiBwcm9jZXNzLmVudi5BVVRIX0dPT0dMRV9TRUNSRVQsCiAgICB9KSwKICBdLAoKICBjYWxsYmFja3M6IHsKICAgIGFzeW5jIGp3dCh7IHRva2VuLCB1c2VyIH0pIHsKICAgICAgaWYgKHVzZXIpIHsKICAgICAgICB0b2tlbi5pZCA9IHVzZXIuaWQ7CiAgICAgICAgdG9rZW4ucm9sZSA9IHVzZXIucm9sZSA/PyAiY3VzdG9tZXIiOwogICAgICB9CiAgICAgIHJldHVybiB0b2tlbjsKICAgIH0sCiAgICBhc3luYyBzZXNzaW9uKHsgc2Vzc2lvbiwgdG9rZW4gfSkgewogICAgICBpZiAodG9rZW4gJiYgc2Vzc2lvbi51c2VyKSB7CiAgICAgICAgc2Vzc2lvbi51c2VyLmlkID0gdG9rZW4uaWQgYXMgc3RyaW5nOwogICAgICAgIHNlc3Npb24udXNlci5yb2xlID0gdG9rZW4ucm9sZSBhcyAiY3VzdG9tZXIiIHwgImFkbWluIjsKICAgICAgfQogICAgICByZXR1cm4gc2Vzc2lvbjsKICAgIH0sCiAgICBhdXRob3JpemVkKHsgYXV0aCwgcmVxdWVzdDogeyBuZXh0VXJsIH0gfSkgewogICAgICBjb25zdCBpc0xvZ2dlZEluID0gISFhdXRoPy51c2VyOwogICAgICBjb25zdCByb2xlID0gYXV0aD8udXNlcj8ucm9sZTsKICAgICAgY29uc3QgeyBwYXRobmFtZSB9ID0gbmV4dFVybDsKCiAgICAgIGlmIChwYXRobmFtZS5zdGFydHNXaXRoKCIvYWRtaW4iKSkgewogICAgICAgIGlmICghaXNMb2dnZWRJbikgcmV0dXJuIGZhbHNlOwogICAgICAgIGlmIChyb2xlICE9PSAiYWRtaW4iKSByZXR1cm4gZmFsc2U7CiAgICAgIH0KCiAgICAgIGlmIChwYXRobmFtZS5zdGFydHNXaXRoKCIvY29udGEiKSkgewogICAgICAgIGlmICghaXNMb2dnZWRJbikgcmV0dXJuIGZhbHNlOwogICAgICB9CgogICAgICByZXR1cm4gdHJ1ZTsKICAgIH0sCiAgfSwKCiAgc2Vzc2lvbjogeyBzdHJhdGVneTogImp3dCIgfSwKfSBzYXRpc2ZpZXMgTmV4dEF1dGhDb25maWc7Cg=="
$path = "$PWD\src\auth.config.ts"
$bytes = [System.Convert]::FromBase64String($b64)
$utf8 = [System.Text.UTF8Encoding]::new($false)
$text = $utf8.GetString($bytes)
[System.IO.File]::WriteAllText($path, $text, $utf8)
Write-Host "  OK src/auth.config.ts" -ForegroundColor Green

# src/auth.ts
$b64 = "aW1wb3J0IE5leHRBdXRoLCB7IHR5cGUgRGVmYXVsdFNlc3Npb24gfSBmcm9tICJuZXh0LWF1dGgiOwppbXBvcnQgQ3JlZGVudGlhbHMgZnJvbSAibmV4dC1hdXRoL3Byb3ZpZGVycy9jcmVkZW50aWFscyI7CmltcG9ydCB7IE1vbmdvREJBZGFwdGVyIH0gZnJvbSAiQGF1dGgvbW9uZ29kYi1hZGFwdGVyIjsKaW1wb3J0IGJjcnlwdCBmcm9tICJiY3J5cHRqcyI7CmltcG9ydCB7IHogfSBmcm9tICJ6b2QiOwoKaW1wb3J0IGF1dGhDb25maWcgZnJvbSAiQC9hdXRoLmNvbmZpZyI7CmltcG9ydCBjbGllbnRQcm9taXNlIGZyb20gIkAvbGliL2RiL21vbmdvLWNsaWVudCI7CmltcG9ydCB7IGNvbm5lY3REQiB9IGZyb20gIkAvbGliL2RiL21vbmdvb3NlIjsKaW1wb3J0IHsgVXNlciB9IGZyb20gIkAvbW9kZWxzL1VzZXIiOwoKZGVjbGFyZSBtb2R1bGUgIm5leHQtYXV0aCIgewogIGludGVyZmFjZSBTZXNzaW9uIHsKICAgIHVzZXI6IHsKICAgICAgaWQ6IHN0cmluZzsKICAgICAgcm9sZTogImN1c3RvbWVyIiB8ICJhZG1pbiI7CiAgICB9ICYgRGVmYXVsdFNlc3Npb25bInVzZXIiXTsKICB9CgogIGludGVyZmFjZSBVc2VyIHsKICAgIHJvbGU/OiAiY3VzdG9tZXIiIHwgImFkbWluIjsKICB9Cn0KCmNvbnN0IGNyZWRlbnRpYWxzU2NoZW1hID0gei5vYmplY3QoewogIGVtYWlsOiB6LnN0cmluZygpLmVtYWlsKCksCiAgcGFzc3dvcmQ6IHouc3RyaW5nKCkubWluKDYpLAp9KTsKCmV4cG9ydCBjb25zdCB7IGhhbmRsZXJzLCBhdXRoLCBzaWduSW4sIHNpZ25PdXQgfSA9IE5leHRBdXRoKHsKICAuLi5hdXRoQ29uZmlnLAoKICBhZGFwdGVyOiBNb25nb0RCQWRhcHRlcihjbGllbnRQcm9taXNlLCB7CiAgICBkYXRhYmFzZU5hbWU6IHByb2Nlc3MuZW52Lk1PTkdPREJfREIgPz8gInhlbmNvIiwKICB9KSwKCiAgcHJvdmlkZXJzOiBbCiAgICAuLi5hdXRoQ29uZmlnLnByb3ZpZGVycywKCiAgICBDcmVkZW50aWFscyh7CiAgICAgIGNyZWRlbnRpYWxzOiB7CiAgICAgICAgZW1haWw6IHsgbGFiZWw6ICJFbWFpbCIsIHR5cGU6ICJlbWFpbCIgfSwKICAgICAgICBwYXNzd29yZDogeyBsYWJlbDogIlBhc3N3b3JkIiwgdHlwZTogInBhc3N3b3JkIiB9LAogICAgICB9LAogICAgICBhc3luYyBhdXRob3JpemUoY3JlZGVudGlhbHMpIHsKICAgICAgICBjb25zdCBwYXJzZWQgPSBjcmVkZW50aWFsc1NjaGVtYS5zYWZlUGFyc2UoY3JlZGVudGlhbHMpOwogICAgICAgIGlmICghcGFyc2VkLnN1Y2Nlc3MpIHJldHVybiBudWxsOwoKICAgICAgICBhd2FpdCBjb25uZWN0REIoKTsKCiAgICAgICAgY29uc3QgdXNlciA9IGF3YWl0IFVzZXIuZmluZE9uZSh7CiAgICAgICAgICBlbWFpbDogcGFyc2VkLmRhdGEuZW1haWwudG9Mb3dlckNhc2UoKSwKICAgICAgICB9KS5zZWxlY3QoIitwYXNzd29yZCIpOwoKICAgICAgICBpZiAoIXVzZXIgfHwgIXVzZXIucGFzc3dvcmQpIHJldHVybiBudWxsOwoKICAgICAgICBjb25zdCB2YWxpZCA9IGF3YWl0IGJjcnlwdC5jb21wYXJlKHBhcnNlZC5kYXRhLnBhc3N3b3JkLCB1c2VyLnBhc3N3b3JkKTsKICAgICAgICBpZiAoIXZhbGlkKSByZXR1cm4gbnVsbDsKCiAgICAgICAgcmV0dXJuIHsKICAgICAgICAgIGlkOiB1c2VyLl9pZC50b1N0cmluZygpLAogICAgICAgICAgZW1haWw6IHVzZXIuZW1haWwsCiAgICAgICAgICBuYW1lOiB1c2VyLm5hbWUsCiAgICAgICAgICByb2xlOiB1c2VyLnJvbGUsCiAgICAgICAgfTsKICAgICAgfSwKICAgIH0pLAogIF0sCn0pOwo="
$path = "$PWD\src\auth.ts"
$bytes = [System.Convert]::FromBase64String($b64)
$utf8 = [System.Text.UTF8Encoding]::new($false)
$text = $utf8.GetString($bytes)
[System.IO.File]::WriteAllText($path, $text, $utf8)
Write-Host "  OK src/auth.ts" -ForegroundColor Green

# src/proxy.ts
$b64 = "aW1wb3J0IE5leHRBdXRoIGZyb20gIm5leHQtYXV0aCI7CmltcG9ydCBhdXRoQ29uZmlnIGZyb20gIkAvYXV0aC5jb25maWciOwoKLyoqCiAqIFByb3h5IGRvIE5leHQuanMgMTYgKHN1YnN0aXR1aSBtaWRkbGV3YXJlLnRzKS4KICoKICogVXNhIGFwZW5hcyBhdXRoQ29uZmlnIChlZGdlLXNhZmUpLCBzZW0gTW9uZ29vc2Ugb3UgYmNyeXB0LgogKiBBIGF1dG9yaXphw6fDo28gw6kgZmVpdGEgcGVsbyBjYWxsYmFjayBgYXV0aG9yaXplZGAgZW0gYXV0aC5jb25maWcudHMKICovCmV4cG9ydCBjb25zdCB7IGF1dGg6IG1pZGRsZXdhcmUgfSA9IE5leHRBdXRoKGF1dGhDb25maWcpOwoKZXhwb3J0IGRlZmF1bHQgbWlkZGxld2FyZSgocmVxKSA9PiB7CiAgLy8gTyBjYWxsYmFjayBgYXV0aG9yaXplZGAgZW0gYXV0aC5jb25maWcudHMgdHJhdGEgZGEgbMOzZ2ljYS4KICAvLyBTZSByZXRvcm5hciBmYWxzZSwgbyB1dGlsaXphZG9yIMOpIHJlZGlyZWNpb25hZG8gcGFyYSAvbG9naW4uCiAgcmV0dXJuOwp9KTsKCmV4cG9ydCBjb25zdCBjb25maWcgPSB7CiAgbWF0Y2hlcjogWwogICAgIi8oKD8hYXBpL2F1dGh8X25leHQvc3RhdGljfF9uZXh0L2ltYWdlfGZhdmljb24uaWNvfGltYWdlc3xmb250c3wuKlxcLig/OnBuZ3xqcGd8anBlZ3xnaWZ8d2VicHxzdmd8aWNvfHdvZmZ8d29mZjIpKS4qKSIsCiAgXSwKfTsK"
$path = "$PWD\src\proxy.ts"
$bytes = [System.Convert]::FromBase64String($b64)
$utf8 = [System.Text.UTF8Encoding]::new($false)
$text = $utf8.GetString($bytes)
[System.IO.File]::WriteAllText($path, $text, $utf8)
Write-Host "  OK src/proxy.ts" -ForegroundColor Green

Write-Host ""
Write-Host "Fix aplicado. Corre: npm run dev" -ForegroundColor Cyan